using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WikiLib.Wikis;
using Xunit;

namespace WikiLib.Tests
{
    public class WikidpadWikiTests
    {
        private readonly string _testDir;
        private readonly string _dataDir;

        public WikidpadWikiTests()
        {
            _testDir = Path.Combine(TestUtilities.SetTestFolder(),"wp");
            _dataDir = Path.Combine(_testDir, "data");
        }


        [Fact]
        public void Constructor_UsesRootWhenNoDataDir()
        {
            //arrange
            if (Directory.Exists(_dataDir))
            {
                Directory.Delete(_dataDir, true);
            }
            var expected = _testDir;
            var sut = new WikidpadWiki(_testDir);
            //actual
            var actual = sut.DataDir;

            //assert
            Assert.Equal(expected, actual);

        }

        [Fact]
        public void Constructor_FindsDataDirWhenExists()
        {
            //arrange
            Directory.CreateDirectory(_dataDir);
            var expected = _dataDir;
            var sut = new WikidpadWiki(_testDir);
            //actual
            var actual = sut.DataDir;

            //assert
            Assert.Equal(expected, actual);

        }



        [Fact]
        public void Constructor_LoadsAllPages()
        {
            Directory.CreateDirectory(_dataDir);
            //arrange
            File.Create(Path.Combine(_dataDir, @"TestOne.wiki"));
            File.Create(Path.Combine(_dataDir, @"TestTwo.wiki"));
            //actual
            var sut = new WikidpadWiki(_testDir);
            
            Assert.Equal("TestOne", sut.Pages[0].Name);
            Assert.Equal("TestTwo", sut.Pages[1].Name);

        }
        
        [Fact]
        public void GetPageContent_GetsContentAndMarksPageAsRead()
        {
            Directory.CreateDirectory(_dataDir);
            //arrange
            var expected = "+ Test One\n\n-This wiki file is generated by tests\n[tag:tests]";
            var expected2 = "+ Test Two\n\n-This wiki file is generated by tests\n[tag:tests] CategoryTests";
            File.WriteAllText(Path.Combine(_dataDir, "TestOne.wiki"), expected);
            File.WriteAllText(Path.Combine(_dataDir, "TestTwo.wiki"), expected2);
            //actual
            var sut = new WikidpadWiki(_testDir);
            
            Assert.Equal(expected, sut.Pages[0].GetPageContent());
            Assert.Equal(expected2, sut.Pages[1].GetPageContent());

            Assert.True(sut.Pages[0].ContentIsStale);            
            Assert.True(sut.Pages[1].ContentIsStale);


        }
    }
}
